### ISSUE TITLE
mac version startup issue

### ISSUE THREAD

**Issue by vikor** [c-darwin/dcoin-go#1]
precondition: OSX 10.9.5, MacBook Pro

I'v tried to start the mac 64 version v1.0.2b10 and v1.0.2b7.
The application v1.0.2b7 crashed and closed after start soon.
The application v1.0.2b10 appeared with white screen and ThrustShell empty menu.
b10 started completely after restart.

**Comment by vikor** [comment]
The issue occurred sporadically, probably related to network error handling

**Comment by c-darwin** [comment]
This is possible when there are problems with the network.
I will fix it.
Thank you!

**Comment by c-darwin** [comment]
fixed
