### ISSUE TITLE
Дублирование авторизации

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#12]
**Windows 7 64-bit**

1 - Запустить приложение.
2 - Зайти в аккаунт, используя ключ и пароль.

**Результат:** В левом меню остаётся кнопка Login.

![zanpap1ily5jkm](https://cloud.githubusercontent.com/assets/10295842/13076877/fb416ba6-d4bd-11e5-9ffa-ccc6c7fa536d.jpg)

**Ожидаемый результат:** Кнопка Login появляется только при длительном бездействии, но не сразу при входе в аккаунт.

**Comment by c-darwin** [comment]
Галочка "сохранить ключ" была установлена?

**Comment by ylomakin** [comment]
Нет, галочка "сохранить ключ" была отключена.

**Comment by ylomakin** [comment]
Fixed
