### ISSUE TITLE
Geolocation crashed

### ISSUE THREAD

**Issue by vikor** [c-darwin/dcoin-go#2]
precondition: OSX 10.9.5, MacBook Pro, app mac 64 version v1.0.2b10 

Application crashed while geolocation processed and Dcoin quit unexpectedly.

Stack trace:

Process:         ThrustShell [87380]
Crashed Thread:  23  Geolocation
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x0000000000000000
—
Thread 0:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff8a213a1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff8a212d18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff8c3c6f15 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff8c3c6539 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff8c3c5e75 CFRunLoopRunSpecific + 309
5   com.apple.HIToolbox           	0x00007fff8d54ea0d RunCurrentEventLoopInMode + 226
6   com.apple.HIToolbox           	0x00007fff8d54e7b7 ReceiveNextEventCommon + 479
7   com.apple.HIToolbox           	0x00007fff8d54e5bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
8   com.apple.AppKit              	0x00007fff8fffa24e _DPSNextEvent + 1434
9   com.apple.AppKit              	0x00007fff8fff989b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
10  com.apple.AppKit              	0x00007fff8ffed99c -[NSApplication run] + 553
11  libchromiumcontent.dylib      	0x0000000108a81521 0x108a63000 + 124193
12  libchromiumcontent.dylib      	0x0000000108a80bdc 0x108a63000 + 121820
13  libchromiumcontent.dylib      	0x0000000108aedcd6 base::RunLoop::Run() + 70
14  libchromiumcontent.dylib      	0x0000000108b82831 content::BrowserMainLoop::MainMessageLoopRun() + 113
15  libchromiumcontent.dylib      	0x0000000108b82795 content::BrowserMainLoop::RunMainMessageLoopParts() + 69
16  libchromiumcontent.dylib      	0x0000000108b84d42 0x108a63000 + 1187138
17  libchromiumcontent.dylib      	0x0000000108b7e907 content::BrowserMain(content::MainFunctionParams const&) + 167
18  libchromiumcontent.dylib      	0x0000000108a74d54 0x108a63000 + 73044
19  libchromiumcontent.dylib      	0x0000000108a74246 content::ContentMain(content::ContentMainParams const&) + 54
20  org.breach.ThrustShellFramework	0x0000000108914b88 ThrustShellMain + 72
21  libdyld.dylib                 	0x00007fff8ab035fd start + 1

**Comment by c-darwin** [comment]
Thank you!
I was able to repeat the bug.
It will be fixed in the new version.

**Comment by c-darwin** [comment]
Fixed
