### ISSUE TITLE
Неправильная установка Standard на Windows 10

### ISSUE THREAD

**Issue by gentee** [c-darwin/dcoin-go#24]
Взял 32x .zip версию, у меня Windows 10. Запустил. В браузере стоит отметка на Standard и я ничего не меняю нажимаю далее. Получаю следующее окно
![step1](https://cloud.githubusercontent.com/assets/2069001/13133615/b7f96a62-d61e-11e5-8b85-387fdf498135.png)
OK. Жду минут 7 и получаю вот это
![step2](https://cloud.githubusercontent.com/assets/2069001/13133624/c75804a0-d61e-11e5-964a-d14abf071282.png)

То есть при стандартной установке началась загрузка блокчейнов. Где-то ошибка.
Буду разбираться.

Я подозреваю, что это не только проблема 32x .zip. У меня вчера все Windows версии уходили на загрузку блокчейнов.

**Comment by gentee** [comment]
Причина оказалась в том, то Касперский 16 без всяких предупреждений что-то портит в TCP соединении в blocks_collection.go. Из-за этого программа в начале уходила в бесконечный цикл, а при повторных запусках в какой-то момент начинала скачивать все блоки с нуля. Если у Касперского добавить исключения в Dcoin.exe - Не проверять сетевую активность, то тогда всё работает нормально. Желательно бы сделать отслеживание таких ситуация и предлагать настроить фаревол.

**Comment by c-darwin** [comment]
Перепроверьте, могло глючить из-за одного бага, который уже исправлен.

**Comment by gentee** [comment]
У меня gcc не понимает objective-c в packages\geolocation. Что для этого надо сделать?

**Comment by gentee** [comment]
С Касперским проблема так и остается - зависает. А если это не считать, то нормально  устанавливается
