### ISSUE TITLE
Broken pipe while signup in the pool

### ISSUE THREAD

**Issue by vikor** [c-darwin/dcoin-go#3]
precondition: OSX 10.9.5, MacBook Pro, app mac 64 version v2.0.1b4

signup, stage 8: "Signup in the pool", obtained the next error message:
The table consist from 1st column, 2nd col.
1st col: "http://pool.dcoin.club"
2nd col: 
"Sign up in the pool: OK"
"Sending data to the pool: write tcp 192.168.1.11->57844->109.120.177.166:8088: write: broken pipe (controllers.(*Controller).SendToPool: 78)"
"Sending data to the pool" (note: waitClock appeared there)

Would be good to give me possibility to copy the error messages from text boxes or tables.

**Comment by c-darwin** [comment]
This is strange. Please write me an darwin@dcoin.club

**Comment by LincolnFaradey** [comment]
the bug is fixed in the news version. Uploaded files exceeded 32mb. Now it's increased up to 64mb.
