### ISSUE TITLE
Повторный вход в аккаунт

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#36]
**Веб версия**

1 - Зайти в аккаунт, используя ключ и пароль.
2 - Обновить страницу (Ctrl+F5).

**Результат:** Запрашивается авторизация

![grqdvdqunxejra](https://cloud.githubusercontent.com/assets/10295842/13173516/9a4e1eb6-d706-11e5-9335-dbe91db80cca.jpg)

**Ожидаемый результат:** Повторный вход в аккаунт не требуется.

**Comment by olegstr** [comment]
На пуле нет возможности сохранять ключ на сервере, т.к. это крайне опасно. Ключ можно сохранять только при работе с локальной версией

**Comment by c-darwin** [comment]
При работе с пулом нет возможности сохранять приватный ключ в БД т.к. это крайне опасно. Ключ можно сохранять только в локальной версии.

**Comment by ylomakin** [comment]
Закрываю.
