### ISSUE TITLE
Don't run the application (Mac OS X 10.11.2) v2.1.0a14

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#44]
1 - Install the app for the first time.
2 - Start the application.
**Result:** Nothing happens, the application does not start.

1 - Впервые установить приложение.
2 - Запустить приложение.
**Результат:** Ничего не происходит, приложение не запускается.

![823nznwi6x47wm](https://cloud.githubusercontent.com/assets/10295842/13202311/ddde1570-d89e-11e5-915a-fb82601bbad1.jpg)

**Comment by LincolnFaradey** [comment]
Check the latest version, 2.1.0a16
the bug is fixed

**Comment by ylomakin** [comment]
Fixed.
