### ISSUE TITLE
Bug synchronization blockchain (Windows 7 64-bit) v2.1.0a14

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#45]
1 - Install the app for the first time.
2 - Select the startup type "Extended".
3 - Clear field "db url" and click Next.
**Result:** There is a process of synchronization blockchain, but very slowly. At 36-38% folded all progress and start from 0%.

1 - Впервые установить приложение.
2 - Выбрать тип запуска "Extended".
3 - Очистить поле db url и нажать Next.
**Результат:** Идёт процесс синхронизации блокчейнов. На 36-38% сбросился весь прогресс и началось с 0%.

[dclog.txt](https://github.com/c-darwin/dcoin-go/files/139609/dclog.txt)

**Comment by c-darwin** [comment]
Нашел проблему. 14:44:34.110 common_parse_data_full.go:152 ParseDataFull [ERRO]  error: [ERROR] incorrect variable system_commission (dcparser.(*Parser).AdminVariablesFront :  63)

**Comment by c-darwin** [comment]
https://github.com/c-darwin/dcoin-go/commit/385194405f6f3875227d33a0cd7b2b61522cfc56
