### ISSUE TITLE
New promised amount can be greater than the maximum (web)

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#46]
1 - Go to the pool
2 - Go to the "Mining / My promised amounts / New promised amount"
3 - Select any type of currency and deposit an amount greater than the specified maximum, choose a way to download videos from Youtube and click Send to the DC-network
![1a5qxqwhkzpkva](https://cloud.githubusercontent.com/assets/10295842/13212888/887a7268-d94d-11e5-9c6e-b7b42b15c1df.jpg)
**Result:** The data is sent to the network and the message is sent successfully.
![eao0r0ys47devr](https://cloud.githubusercontent.com/assets/10295842/13212944/ea9fa24c-d94d-11e5-8ab4-0f25e9f503dc.jpg)
**Expected Result:** The data is not sent, it should be a message about exceeding the limit or validation of the field "Amount".

1 - Зайти на пулл
2 - Перейти на "Майнинг / Мои обещанные суммы / Новая обещанная сумма"
3 - Выбрать любой тип валюты и ввести сумму больше указанного максимума, выбрать способ загрузки видео с Youtube и нажать кнопку Отправить в DC-сеть
**Результат:** Данные отправляются в сеть и появляется сообщение об успешной отправке.
**Ожидаемый результат:** Данные не отправляются, должно быть сообщение про превышенный лимит или валидация поля "Количество".

**Comment by rpoletaev** [comment]
нужно, чтобы клиент не мог отправить данные или чтобы с сервера пришел ответ с ошибкой?

**Comment by rpoletaev** [comment]
Что делать в случае, если максимальная сумма указана как 0? Считать, что ограничения нет или что нельзя вводить новую обещанную сумму?

**Comment by ylomakin** [comment]
По второму вопросу - я думаю, что лучше чтобы не смог отправить.
Но а там уже как надёжнее.

По второму вопросу - логично сделать: если 0, то поле disabled, если не указана - считать ограничения нет.

**Comment by c-darwin** [comment]
Если 0, то добавить не получится. Неуказанной максимальной быть не может. Отсутствие ограничения на обещанную сумму - это абсурд.

**Comment by rpoletaev** [comment]
Или абсурд или ошибка, думал, что может лучше проверить и отреагировать

**Comment by c-darwin** [comment]
@rpoletaev, всё правильно, багов у нас много ) про абсурд - это я не про интерфейс, а про саму логику, если бы можно было добавить $1трл, то очень быстро появились бы миллиарды dUSD и валюта мгновенно обесценилась бы.

**Comment by rpoletaev** [comment]
ок, тогда этим и займусь пока.

**Comment by c-darwin** [comment]
@rpoletaev, сделал что-нибудь по этой задаче? Если нет, то передаю другому, т.к. баг важный и в новый релиз попасть не должен.

**Comment by rpoletaev** [comment]
только в клиенте немного поправил, могу залить через 5 мин, а дальше пусть другой смотрит что на сервере нужно сделать

**Comment by c-darwin** [comment]
Заливай конечно. В ветку dev

**Comment by rpoletaev** [comment]
Уже
3 марта 2016 г. 2:07 PM пользователь "c-darwin" <notifications@github.com>
написал:

**Comment by c-darwin** [comment]
@rpoletaev не вижу, дай ссылку на коммит

**Comment by rpoletaev** [comment]
https://github.com/rpoletaev/dcoin-go/commit/72ad3f21258dd74d1f974b63bed069bd892d2f21

3 марта 2016 г., 14:08 пользователь Poletaev Roman <losaped@gmail.com>
написал:

> Уже
> 3 марта 2016 г. 2:07 PM пользователь "c-darwin" <notifications@github.com>
> написал:
>
>> Заливай конечно. В ветку dev
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/c-darwin/dcoin-go/issues/46#issuecomment-191710330>.
>>
>


-- 
Ваш воин ночи

**Comment by ylomakin** [comment]
В релизе v2.1.0a19 я не заметил никаких изменений.

**Comment by ylomakin** [comment]
Проверил, появляется сообщение.
Но сообщение НЕ появляется при цифре 1, при других суммах всегда появляется, даже если сумма меньше максимума

**Comment by rpoletaev** [comment]
Ребят, у меня не получается время уделять. Так что пусть кто-нить берет себе баг

**Comment by ylomakin** [comment]
Я поправил
