### ISSUE TITLE
Cann't go back to the login page in account (all OS and web) v2.1.0a15

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#48]
1 - Start application (initial installation) or go to the pool
2 - Click "Sign up"
3 - Come up with a password and download key
![l21pxpwi6wj4dm](https://cloud.githubusercontent.com/assets/10295842/13244523/88fdcb5a-da0f-11e5-80ff-785fccfa7bb2.jpg)

**Result:** You can not go back to the login page in your account.
**Expected Result:** After downloading a key, there is a "sign in" button or you can skip the page Login / Sign up.

1 - Запустить приложение (первичная установка) или зайти на пулл
2 - Нажать кнопку "Зарегистрироваться"
3 - Придумать пароль и скачать ключ

**Результат:** Нельзя вернуться на страницу входа в аккаунт.
**Ожидаемый результат:** После скачивания ключа, появляется кнопка "войти в аккаунт" или осуществляется переход на страницу Вход/Регистрания.

**Comment by gentee** [comment]
Я переделал немного сам алгоритм регистрации. Попробуй взять файлы из pull request
https://github.com/c-darwin/dcoin-go/pull/56. Эта проблема должна исчезнуть.

**Comment by ylomakin** [comment]
Fixed
