### ISSUE TITLE
Переход на 3-й и 4-й шаг не загружая фото

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#5]
1 - Зарегистрироваться на http://pool.dcoin.club
2 - Зайти в аккаунт, используя ключ и пароль.
3 - Выбрать тип аккаунта Майнер.
4 - На втором и третьем шаге ничего не загружать.

**Результат:** Доходим до 4-го шага без проблем.

![dr8w4wwfkvdbja](https://cloud.githubusercontent.com/assets/10295842/13049040/aea25308-d3f2-11e5-876b-38af056f6201.jpg)

**Ожидаемый результат:** Появляется сообщение про обязательную загрузку фотографии, при этом переход на следующий шаг не происходит

**Comment by c-darwin** [comment]
![d-1024](https://cloud.githubusercontent.com/assets/7119525/13048998/c598c4e0-d3fa-11e5-91b3-39f7b4a5756e.png)
тест

**Comment by ylomakin** [comment]
Fixed
