### ISSUE TITLE
Register without email (Windows 7 64-bit, Windows 10 64-bit) v2.1.0a14

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#52]
1 - Completely uninstall the application and install again after all the steps in #48
2 - Run the app and click "Register"
**Result:** No window, indicating e-mail, directly to a page "Set password".

1 - Полностью удалить приложение и установить снова после всех шагов в #48
2 - Запустить приложение и нажать кнопку "Зарегистрироваться"
**Результат:** Нет окна с указанием e-mail, сразу переходит на страницу "Установка пароля".

**Comment by gentee** [comment]
Окно с указанием Email появляется только, когда идет регистрация в пуле. Если вы локально устанавливайте dcoin,exe, то он не спрашивает email.
