### ISSUE TITLE
Failed to upgrade account (Windows 10 64-bit) v2.1.0a16

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#54]
1 - Completely remove the app and install again.
2 - Start the app and click "Register" button.
3 - Go to the application.
4 - Select account type "miner" and go through all the steps up to the 6th.
5 - Click "Save and goto step 7".
**Result:** Go to Step 7 is not carried out, there is a blank page.

![drl7b7yi4jlxla](https://cloud.githubusercontent.com/assets/10295842/13315549/fb312992-dbb3-11e5-95f1-3fb0801e2fd9.jpg)

1 - Полностью удалить приложение и установить снова.
2 - Запустить приложение и нажать кнопку "Зарегистрироваться".
3 - Зайти в приложение.
4 - Выбрать тип аккаунта "майнер" и пройти все шаги до 6-го.
5 - Нажать "Сохранить".
**Результат:** Переход на 7-й шаг не осуществляется, появляется пустая страница.

**Comment by ylomakin** [comment]
Исправлено.
Но появился новый баг.
1 - Корректно заполнить все 7 шагов.

**Результат:** Показывает ошибку "Не указан адрес ноды. Пожалуйста, вернитесь на шаг 5."
![52anvnkfgv05ba](https://cloud.githubusercontent.com/assets/10295842/13364571/3c11c12c-dcd8-11e5-9e72-2f9ce4cf6157.jpg)

**Comment by c-darwin** [comment]
@ylomakin покажи скриншот 7-го шага

**Comment by ylomakin** [comment]
![ba0n1nwib4xq9m](https://cloud.githubusercontent.com/assets/10295842/13381808/a4e8f148-de6d-11e5-87e9-73383a9dcb32.jpg)

Ввожу e-mail и нажимаю кнопку Next
Вот это успел отловить скринами
![n2yrzresjnb08a](https://cloud.githubusercontent.com/assets/10295842/13381817/e9090a98-de6d-11e5-9995-f97791f52651.jpg)
![q2kdldxs9wegya](https://cloud.githubusercontent.com/assets/10295842/13381818/f709731c-de6d-11e5-9854-2f764c918ba2.jpg)

Ну и в конце
![52anvnkfgvqzva](https://cloud.githubusercontent.com/assets/10295842/13381825/3966e26c-de6e-11e5-97c5-be504f5b22d3.jpg)

**Comment by ylomakin** [comment]
Fixed

**Comment by ylomakin** [comment]
Новый баг.
1 - сделать полный апгрейд.
**Результат:** Появляется сообщение, что проверка данных займёт какое-то время. Спустя минут 15 выдаётся ошибка.
![p276b6wh0vnn1m](https://cloud.githubusercontent.com/assets/10295842/13491605/07851c34-e13c-11e5-97dd-b11827bf8edc.jpg)

**Comment by ylomakin** [comment]
Fixed
