### ISSUE TITLE
Нельзя загружать видео через вебкамеру

### ISSUE THREAD

**Issue by ylomakin** [c-darwin/dcoin-go#6]
1 - Зайти в аккаунт, используя ключ и пароль.
2 - Выбрать тип аккаунта Майнер.
3 - На четвёртом шаге выбрать способ загрузки видео Webcam

**Результат:** 
![bmo606nhmdokgr](https://cloud.githubusercontent.com/assets/10295842/13050663/901a38a0-d3fd-11e5-8b2f-02d9379518a0.jpg)
Также похожая ситуация с #5 (можно не загружая видео перейти на следующий шаг)

**Ожидаемый результат:** Видео можно загружать через веб-камеру.

**Comment by ylomakin** [comment]
Вот что пишет гугл https://support.google.com/youtube/answer/57409?hl
Выходит нужно убирать возможность загружать с вебки, либо искать новое решение.

**Comment by c-darwin** [comment]
Да, надо убрать

**Comment by gentee** [comment]
Убрано в commit #73 
Подобна я запись с веб камеры еще есть в new_promised_amount_html. Там тоже убирать?

**Comment by ylomakin** [comment]
Fixed
