### ISSUE TITLE
Что за страница upgrade?

### ISSUE THREAD

**Issue by gentee** [c-darwin/dcoin-go#68]
Когда захожу на Смена node-ключа, то вижу следующее
![node1](https://cloud.githubusercontent.com/assets/2069001/13485378/075c3048-e129-11e5-8de0-30c2f08d91ac.png)

Когда нажимаю сделать адгрейд, то получаю Access denied 0. Если добавляю upgrade в список допустимых контроллеров, то ошибка исчезает, но появляется сообщение method not found. И действительно файла upgrade.go нет, хотя сам шаблон upgrade.html существует и "upgrade" встречается как возможное имя шаблона в content.go.

Непонятно, то ли upgrade.go был по ошибке удален, переименован или отказались от него, а в Смене node-ключа ссылку исправить забыли.

**Comment by c-darwin** [comment]
надо заменить на upgrade0

**Comment by gentee** [comment]
Исправлено в commit #73
